### ISSUE TITLE
Consider joining dfu-rs

### ISSUE THREAD

**Issue by cecton** [dfu-rs/cargo-dfu#1]
Hello :wave: 

I made the GitHub organization dfu-rs in hope to add more projects related to DFU stuff in Rust.

I don't have a lot of free time but I would be willing to help to do some maintenance on cargo-dfu if you want to help on dfu-core et dfu-libusb.

I propose we move your repository cargo-dfu to the dfu-rs org and I'll give you admin privileges on the organization.

What do you think?

**Comment by gnxlxnxx** [comment]
Yeah, I think this seems like a good idea. 
I think we should do it.

**Comment by cecton** [comment]
Great!

I just sent you an invite. Once it's done you can move cargo-dfu to the organization yourself. Hopefully I won't need to validate anything.

(Obviously I won't be changing or pushing anything to your repository without a PR and review from you no worry.)

Best!

**Comment by gnxlxnxx** [comment]
I think this should be it, I moved the repo, changed the address in  and created a new release.

> (Obviously I won't be changing or pushing anything to your repository without a PR and review from you no worry.)

Didn't have any worries there, I will follow the same philosophy for `dfu-core` and `dfu-libusb`.
